spring:
  datasource:
    url: jdbc:postgresql://container-2.int.henrikssons.org:5432/postgres #jdbc:postgresql://postgres/postgres
    username: begh
    password: hemligt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,uptime"

auth:
  redirectUri: https://api.imats.se/visma-auth-service/login/oauth2/code/visma
  clientId: imatsab
  clientSecret: M2wAPQ2Y8Q25YHoLEkoA40B4Cv72f6XZGF7ZYZK91380AY98O07R8D7hVMy1vF8