spring:
  datasource:
    url: jdbc:postgresql://postgres/postgres #jdbc:postgresql://container-2.int.henrikssons.org:5432/postgres #jdbc:postgresql://postgres/postgres
    username: begh
    password: hemligt
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "health,info,uptime"